---
# K3s version to be installed
kube_version: v1.22.3+k3s1
# Token to login in K3s and the Kubernetes Dashboard
kube_admin_token: kube-token123
# Password for OSCAR
oscar_password: oscar123
# DNS name for the OSCAR Ingress and Kubernetes Dashboard (path "/dashboard/")
dns_host: oscar-cluster.example.com
# Password for MinIO
minio_password: minio123
# DNS name for the MinIO API Ingress
minio_dns_host: minio.oscar-cluster.example.com
# DNS name for the MinIO Console Ingress
minio_dns_host_console: minio-console.oscar-cluster.example.com
