apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oscar-pvc
  namespace: oscar-svc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  resources:
    requests:
      storage: 2Gi
