name: mkdocs

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mkdocs
        python -m pip install mkdocs-material
        python -m pip install mkdocs-render-swagger-plugin
    - name: Build and deploy to gh-pages
      run: |
        git branch -B gh-pages
        git checkout -t origin/gh-pages
        git checkout master
        mkdocs gh-deploy